"""
Catalogue Curaté des Top 100 Entreprises IT Mondiales & Régionales (France & Tunisie)
avec leurs plateformes carrières et signatures d'ingestion directe.
"""

from typing import Any

TOP_100_COMPANIES: list[dict[str, Any]] = [
    # =========================================================================
    # 1. BIG 4 & CONSEIL TECH / STRATÉGIE (France & Tunisie)
    # =========================================================================
    {
        "id": "ey",
        "name": "EY (Ernst & Young)",
        "category": "Big 4 & Conseil Tech",
        "country": "France",
        "careers_url": "https://ey.taleo.net/careersection/gexp_external/jobsearch.ftl",
        "ats_type": "workday_or_taleo",
        "portal_id": "ey",
        "keywords": ["PFE", "Stage", "Data", "Cyber", "Cloud"],
    },
    {
        "id": "ey_tunisia",
        "name": "EY Tunisie (Tunis Hub)",
        "category": "Big 4 & Conseil Tech",
        "country": "Tunisie",
        "careers_url": "https://www.ey.com/fr_tn/careers",
        "ats_type": "custom",
        "keywords": ["PFE", "Stage", "Ingénieur", "IT"],
    },
    {
        "id": "deloitte",
        "name": "Deloitte",
        "category": "Big 4 & Conseil Tech",
        "country": "France",
        "careers_url": "https://deloitte.com/fr/careers",
        "ats_type": "smartrecruiters",
        "portal_id": "deloittefr",
        "keywords": ["Stage", "PFE", "Cyber", "Cloud", "IA"],
    },
    {
        "id": "pwc",
        "name": "PwC France & Maghreb",
        "category": "Big 4 & Conseil Tech",
        "country": "France",
        "careers_url": "https://pwc.wd3.myworkdayjobs.com/Global_Experienced_Careers",
        "ats_type": "workday",
        "portal_id": "pwc",
        "keywords": ["Stage", "PFE", "Data", "Cloud"],
    },
    {
        "id": "pwc_tunisia",
        "name": "PwC Tunisie",
        "category": "Big 4 & Conseil Tech",
        "country": "Tunisie",
        "careers_url": "https://www.pwc.com/tn/fr/carrieres.html",
        "ats_type": "custom",
        "keywords": ["PFE", "Stage", "IT"],
    },
    {
        "id": "kpmg",
        "name": "KPMG France",
        "category": "Big 4 & Conseil Tech",
        "country": "France",
        "careers_url": "https://kpmg.com/fr/fr/home/carrieres.html",
        "ats_type": "workday",
        "portal_id": "kpmg",
        "keywords": ["Stage", "PFE", "Data", "Cybersécurité"],
    },
    {
        "id": "accenture",
        "name": "Accenture",
        "category": "Big 4 & Conseil Tech",
        "country": "France",
        "careers_url": "https://accenture.wd3.myworkdayjobs.com/Accenture_Careers",
        "ats_type": "workday",
        "portal_id": "accenture",
        "keywords": ["Stage", "PFE", "Cloud", "IA", "DevOps"],
    },
    {
        "id": "wavestone",
        "name": "Wavestone",
        "category": "Big 4 & Conseil Tech",
        "country": "France",
        "careers_url": "https://www.wavestone.com/fr/carrieres/",
        "ats_type": "smartrecruiters",
        "portal_id": "wavestone",
        "keywords": ["Stage", "PFE", "Cybersécurité", "Cloud"],
    },
    {
        "id": "sia_partners",
        "name": "Sia Partners",
        "category": "Big 4 & Conseil Tech",
        "country": "France",
        "careers_url": "https://www.sia-partners.com/fr/carrieres",
        "ats_type": "smartrecruiters",
        "portal_id": "siapartners",
        "keywords": ["Stage", "Data Science", "IA", "PFE"],
    },
    {
        "id": "bearingpoint",
        "name": "BearingPoint",
        "category": "Big 4 & Conseil Tech",
        "country": "France",
        "careers_url": "https://bearingpoint.com/fr/carrieres/",
        "ats_type": "smartrecruiters",
        "portal_id": "bearingpoint",
        "keywords": ["Stage", "PFE", "Consultant IT"],
    },

    # =========================================================================
    # 2. PÉPITES & LEADERS TECH / AI / FINTECH EN TUNISIE
    # =========================================================================
    {
        "id": "instadeep",
        "name": "InstaDeep (BioNTech)",
        "category": "Leaders Tech & AI Tunisie",
        "country": "Tunisie",
        "careers_url": "https://boards-api.greenhouse.io/v1/boards/instadeep/jobs",
        "ats_type": "greenhouse",
        "portal_id": "instadeep",
        "keywords": ["Intern", "Research", "AI", "Machine Learning", "Software"],
    },
    {
        "id": "vermeg",
        "name": "Vermeg",
        "category": "Leaders Tech & AI Tunisie",
        "country": "Tunisie",
        "careers_url": "https://www.vermeg.com/careers/",
        "ats_type": "custom",
        "keywords": ["PFE", "Stage", "Java", "Spring", "Angular", "Fintech"],
    },
    {
        "id": "expensya",
        "name": "Expensya (Medius)",
        "category": "Leaders Tech & AI Tunisie",
        "country": "Tunisie",
        "careers_url": "https://careers.expensya.com/",
        "ats_type": "lever",
        "portal_id": "expensya",
        "keywords": ["Intern", "PFE", "Backend", "Frontend", "Cloud"],
    },
    {
        "id": "telnet",
        "name": "Telnet Holding",
        "category": "Leaders Tech & AI Tunisie",
        "country": "Tunisie",
        "careers_url": "http://www.groupe-telnet.com/carrieres",
        "ats_type": "custom",
        "keywords": ["PFE", "Embarqué", "IoT", "C++", "Linux", "Aéronautique"],
    },
    {
        "id": "sofrecom_tunisie",
        "name": "Sofrecom Tunisie (Orange Group)",
        "category": "Leaders Tech & AI Tunisie",
        "country": "Tunisie",
        "careers_url": "https://www.sofrecom.com/carrieres",
        "ats_type": "smartrecruiters",
        "portal_id": "sofrecomtunisie",
        "keywords": ["PFE", "Stage", "Fullstack", "DevOps", "Data", "IA"],
    },
    {
        "id": "focus_corporation",
        "name": "Focus Corporation",
        "category": "Leaders Tech & AI Tunisie",
        "country": "Tunisie",
        "careers_url": "https://www.focus-corporation.com/careers/",
        "ats_type": "custom",
        "keywords": ["PFE", "Stage", "Automotive", "Embedded", "Cloud", "SAP"],
    },
    {
        "id": "wevioo",
        "name": "Wevioo",
        "category": "Leaders Tech & AI Tunisie",
        "country": "Tunisie",
        "careers_url": "https://www.wevioo.com/fr/carrieres",
        "ats_type": "custom",
        "keywords": ["PFE", "Stage", "IA", "DevOps", "Java", "React"],
    },
    {
        "id": "vneuron",
        "name": "Vneuron",
        "category": "Leaders Tech & AI Tunisie",
        "country": "Tunisie",
        "careers_url": "https://www.vneuron.com/careers/",
        "ats_type": "custom",
        "keywords": ["PFE", "Stage", "Fintech", "Compliance", "Python", "Java"],
    },
    {
        "id": "proxym_group",
        "name": "Proxym Group",
        "category": "Leaders Tech & AI Tunisie",
        "country": "Tunisie",
        "careers_url": "https://www.proxym-group.com/careers/",
        "ats_type": "custom",
        "keywords": ["PFE", "Stage", "Mobile", "Flutter", "Web", "Cloud"],
    },
    {
        "id": "actia_engineering",
        "name": "ACTIA Engineering Services",
        "category": "Leaders Tech & AI Tunisie",
        "country": "Tunisie",
        "careers_url": "https://www.actia.com/carrieres/",
        "ats_type": "custom",
        "keywords": ["PFE", "Stage", "Automotive", "Embarqué", "C++", "Diagnostic"],
    },
    {
        "id": "bfi_groupe",
        "name": "BFI Groupe",
        "category": "Leaders Tech & AI Tunisie",
        "country": "Tunisie",
        "careers_url": "https://www.bfi-groupe.com/carrieres",
        "ats_type": "custom",
        "keywords": ["PFE", "Stage", "Banking", "Fintech", "Oracle", "Java"],
    },
    {
        "id": "cynapsys",
        "name": "Cynapsys (Apside Group)",
        "category": "Leaders Tech & AI Tunisie",
        "country": "Tunisie",
        "careers_url": "https://www.cynapsys.de/careers",
        "ats_type": "custom",
        "keywords": ["PFE", "Stage", "Fullstack", "DevOps"],
    },
    {
        "id": "medianet",
        "name": "Medianet Tunisie",
        "category": "Leaders Tech & AI Tunisie",
        "country": "Tunisie",
        "careers_url": "https://www.medianet.tn/fr/recrutement",
        "ats_type": "custom",
        "keywords": ["PFE", "Stage", "Web", "Digital", "Data"],
    },
    {
        "id": "sagemcom_tunisie",
        "name": "Sagemcom Tunisie",
        "category": "Leaders Tech & AI Tunisie",
        "country": "Tunisie",
        "careers_url": "https://www.sagemcom.com/fr/carrieres",
        "ats_type": "smartrecruiters",
        "portal_id": "sagemcom",
        "keywords": ["PFE", "Stage", "Telecom", "Embarqué", "Réseau"],
    },
    {
        "id": "enova_robotics",
        "name": "Enova Robotics",
        "category": "Leaders Tech & AI Tunisie",
        "country": "Tunisie",
        "careers_url": "https://www.enovarobotics.com/careers",
        "ats_type": "custom",
        "keywords": ["PFE", "Robotique", "ROS", "Vision", "IA"],
    },
    {
        "id": "kaoun",
        "name": "Kaoun / Flouci",
        "category": "Leaders Tech & AI Tunisie",
        "country": "Tunisie",
        "careers_url": "https://flouci.com/careers",
        "ats_type": "custom",
        "keywords": ["PFE", "Fintech", "Mobile", "Backend", "Go"],
    },
    {
        "id": "advyteam",
        "name": "Advyteam",
        "category": "Leaders Tech & AI Tunisie",
        "country": "Tunisie",
        "careers_url": "https://www.advyteam.com/carrieres",
        "ats_type": "custom",
        "keywords": ["PFE", "Stage", "HR Tech", "Java", "Consulting"],
    },

    # =========================================================================
    # 3. GÉANTS DU NUMÉRIQUE & ESN D'ÉLITE (France & Tunisie)
    # =========================================================================
    {
        "id": "capgemini",
        "name": "Capgemini",
        "category": "ESN & Grands Groupes IT",
        "country": "France",
        "careers_url": "https://www.capgemini.com/fr-fr/carrieres/",
        "ats_type": "smartrecruiters",
        "portal_id": "capgemini",
        "keywords": ["Stage", "PFE", "Cloud", "IA", "DevOps", "Java"],
    },
    {
        "id": "sopra_steria",
        "name": "Sopra Steria",
        "category": "ESN & Grands Groupes IT",
        "country": "France",
        "careers_url": "https://www.soprasteria.fr/carrieres",
        "ats_type": "smartrecruiters",
        "portal_id": "soprasteria",
        "keywords": ["Stage", "PFE", "Cybersécurité", "Cloud", "IA"],
    },
    {
        "id": "talan",
        "name": "Talan Group (France & Tunisie)",
        "category": "ESN & Grands Groupes IT",
        "country": "France",
        "careers_url": "https://talan.com/carrieres/",
        "ats_type": "smartrecruiters",
        "portal_id": "talan",
        "keywords": ["Stage", "PFE", "Data", "IA", "Cloud", "Agile"],
    },
    {
        "id": "talan_tunisie",
        "name": "Talan Tunisie (Innovation Factory Tunis)",
        "category": "ESN & Grands Groupes IT",
        "country": "Tunisie",
        "careers_url": "https://talan.com/carrieres/",
        "ats_type": "smartrecruiters",
        "portal_id": "talantunisie",
        "keywords": ["PFE", "Stage", "Data Science", "Blockchain", "Cloud", "DevOps"],
    },
    {
        "id": "devoteam",
        "name": "Devoteam",
        "category": "ESN & Grands Groupes IT",
        "country": "France",
        "careers_url": "https://france.devoteam.com/carrieres/",
        "ats_type": "smartrecruiters",
        "portal_id": "devoteam",
        "keywords": ["Stage", "PFE", "AWS", "Google Cloud", "Azure", "Cyber"],
    },
    {
        "id": "inetum",
        "name": "Inetum (France & Tunisie)",
        "category": "ESN & Grands Groupes IT",
        "country": "France",
        "careers_url": "https://www.inetum.com/fr/carrieres",
        "ats_type": "smartrecruiters",
        "portal_id": "inetum",
        "keywords": ["Stage", "PFE", "SAP", "Java", "Cloud"],
    },
    {
        "id": "alten",
        "name": "Alten",
        "category": "ESN & Grands Groupes IT",
        "country": "France",
        "careers_url": "https://www.altenrecrute.fr/",
        "ats_type": "smartrecruiters",
        "portal_id": "alten",
        "keywords": ["Stage", "PFE", "Ingénieur", "Aéronautique", "Embarqué"],
    },
    {
        "id": "akkodis",
        "name": "Akkodis (Adecco Tech)",
        "category": "ESN & Grands Groupes IT",
        "country": "France",
        "careers_url": "https://www.akkodis.com/fr/careers",
        "ats_type": "smartrecruiters",
        "portal_id": "akkodis",
        "keywords": ["Stage", "PFE", "Smart Industry", "Digital", "IT"],
    },
    {
        "id": "aubay",
        "name": "Aubay",
        "category": "ESN & Grands Groupes IT",
        "country": "France",
        "careers_url": "https://www.aubay.com/carrieres/",
        "ats_type": "smartrecruiters",
        "portal_id": "aubay",
        "keywords": ["Stage", "PFE", "Banque", "Finance", "Fullstack"],
    },
    {
        "id": "sqli",
        "name": "SQLI Digital Experience",
        "category": "ESN & Grands Groupes IT",
        "country": "France",
        "careers_url": "https://www.sqli.com/fr-fr/carrieres",
        "ats_type": "smartrecruiters",
        "portal_id": "sqli",
        "keywords": ["Stage", "PFE", "E-commerce", "React", "Node", "Java"],
    },
    {
        "id": "neurones",
        "name": "Neurones IT",
        "category": "ESN & Grands Groupes IT",
        "country": "France",
        "careers_url": "https://www.neurones.net/carrieres",
        "ats_type": "smartrecruiters",
        "portal_id": "neurones",
        "keywords": ["Stage", "PFE", "Cloud", "Infogérance", "DevOps"],
    },
    {
        "id": "econocom",
        "name": "Econocom",
        "category": "ESN & Grands Groupes IT",
        "country": "France",
        "careers_url": "https://carrieres.econocom.com/",
        "ats_type": "smartrecruiters",
        "portal_id": "econocom",
        "keywords": ["Stage", "PFE", "Workplace", "Cloud", "Infrastructure"],
    },
    {
        "id": "cgi",
        "name": "CGI France",
        "category": "ESN & Grands Groupes IT",
        "country": "France",
        "careers_url": "https://www.cgi.com/france/fr-fr/carrieres",
        "ats_type": "custom",
        "keywords": ["Stage", "PFE", "Consultant", "Développeur", "Cloud"],
    },
    {
        "id": "expleo",
        "name": "Expleo Group",
        "category": "ESN & Grands Groupes IT",
        "country": "France",
        "careers_url": "https://expleogroup.com/careers/",
        "ats_type": "smartrecruiters",
        "portal_id": "expleo",
        "keywords": ["Stage", "PFE", "Ingénierie", "Logiciel", "IA"],
    },
    {
        "id": "smile",
        "name": "Smile Open Source",
        "category": "ESN & Grands Groupes IT",
        "country": "France",
        "careers_url": "https://www.smile.eu/fr/carrieres",
        "ats_type": "smartrecruiters",
        "portal_id": "smile",
        "keywords": ["Stage", "PFE", "Open Source", "Linux", "PHP", "Python"],
    },
    {
        "id": "zenika",
        "name": "Zenika",
        "category": "ESN & Grands Groupes IT",
        "country": "France",
        "careers_url": "https://zenika.com/careers",
        "ats_type": "lever",
        "portal_id": "zenika",
        "keywords": ["Stage", "PFE", "Craftsmanship", "Go", "Rust", "Cloud"],
    },
    {
        "id": "octo_technology",
        "name": "Octo Technology (Accenture)",
        "category": "ESN & Grands Groupes IT",
        "country": "France",
        "careers_url": "https://www.octo.com/fr/carrieres/",
        "ats_type": "smartrecruiters",
        "portal_id": "octotechnology",
        "keywords": ["Stage", "PFE", "Architecture", "Cloud Native", "DevOps"],
    },
    {
        "id": "hardis_group",
        "name": "Hardis Group",
        "category": "ESN & Grands Groupes IT",
        "country": "France",
        "careers_url": "https://www.hardis-group.com/carrieres",
        "ats_type": "smartrecruiters",
        "portal_id": "hardisgroup",
        "keywords": ["Stage", "PFE", "Cloud", "Logistique", "Salesforce"],
    },
    {
        "id": "infotel",
        "name": "Infotel",
        "category": "ESN & Grands Groupes IT",
        "country": "France",
        "careers_url": "https://infotel.com/carrieres/",
        "ats_type": "smartrecruiters",
        "portal_id": "infotel",
        "keywords": ["Stage", "PFE", "Grand Système", "Java", "Data"],
    },
    {
        "id": "davidson",
        "name": "Davidson Consulting",
        "category": "ESN & Grands Groupes IT",
        "country": "France",
        "careers_url": "https://www.davidson.fr/carrieres/",
        "ats_type": "smartrecruiters",
        "portal_id": "davidson",
        "keywords": ["Stage", "PFE", "Télécoms", "Cloud", "Software"],
    },

    # =========================================================================
    # 4. BIG TECH & ÉDITEURS MONDIAUX (Bureaux & R&D France & Tunisie)
    # =========================================================================
    {
        "id": "google",
        "name": "Google (Paris R&D Hub)",
        "category": "Big Tech & Éditeurs",
        "country": "France",
        "careers_url": "https://careers.google.com/jobs/results/?location=Paris,%20France",
        "ats_type": "custom",
        "keywords": ["Intern", "Software Engineer", "Machine Learning", "Research"],
    },
    {
        "id": "microsoft",
        "name": "Microsoft France (Issy R&D)",
        "category": "Big Tech & Éditeurs",
        "country": "France",
        "careers_url": "https://careers.microsoft.com/",
        "ats_type": "custom",
        "keywords": ["Intern", "Azure", "Cloud Solution Architect", "Software"],
    },
    {
        "id": "amazon_aws",
        "name": "Amazon & AWS France",
        "category": "Big Tech & Éditeurs",
        "country": "France",
        "careers_url": "https://amazon.jobs/en/locations/paris-france",
        "ats_type": "custom",
        "keywords": ["Intern", "Software Development", "Solutions Architect"],
    },
    {
        "id": "meta",
        "name": "Meta (FAIR Paris Lab)",
        "category": "Big Tech & Éditeurs",
        "country": "France",
        "careers_url": "https://www.metacareers.com/locations/paris/",
        "ats_type": "custom",
        "keywords": ["Intern", "Research Scientist", "AI", "PyTorch"],
    },
    {
        "id": "apple",
        "name": "Apple France (R&D Lab)",
        "category": "Big Tech & Éditeurs",
        "country": "France",
        "careers_url": "https://jobs.apple.com/fr-fr/search?location=france-FRAC",
        "ats_type": "custom",
        "keywords": ["Intern", "Software", "Hardware", "Machine Learning"],
    },
    {
        "id": "datadog",
        "name": "Datadog (Paris Engineering R&D)",
        "category": "Big Tech & Éditeurs",
        "country": "France",
        "careers_url": "https://boards-api.greenhouse.io/v1/boards/datadog/jobs",
        "ats_type": "greenhouse",
        "portal_id": "datadog",
        "keywords": ["Intern", "Software Engineer", "Backend", "Go", "Distributed"],
    },
    {
        "id": "criteo",
        "name": "Criteo (AI Lab Paris)",
        "category": "Big Tech & Éditeurs",
        "country": "France",
        "careers_url": "https://boards-api.greenhouse.io/v1/boards/criteo/jobs",
        "ats_type": "greenhouse",
        "portal_id": "criteo",
        "keywords": ["Intern", "Machine Learning", "Software Engineer", "Data"],
    },
    {
        "id": "ibm",
        "name": "IBM France & Client Center",
        "category": "Big Tech & Éditeurs",
        "country": "France",
        "careers_url": "https://www.ibm.com/careers/fr-fr/",
        "ats_type": "smartrecruiters",
        "portal_id": "ibm",
        "keywords": ["Stage", "PFE", "Quantum", "Cloud", "Red Hat", "IA"],
    },
    {
        "id": "sap",
        "name": "SAP Labs France",
        "category": "Big Tech & Éditeurs",
        "country": "France",
        "careers_url": "https://jobs.sap.com/",
        "ats_type": "workday",
        "portal_id": "sap",
        "keywords": ["Intern", "PFE", "Cloud ERP", "HANA", "Java"],
    },
    {
        "id": "cisco",
        "name": "Cisco Systems",
        "category": "Big Tech & Éditeurs",
        "country": "France",
        "careers_url": "https://jobs.cisco.com/",
        "ats_type": "workday",
        "portal_id": "cisco",
        "keywords": ["Intern", "Network", "Security", "Software"],
    },
    {
        "id": "oracle",
        "name": "Oracle France",
        "category": "Big Tech & Éditeurs",
        "country": "France",
        "careers_url": "https://oracle.taleo.net/careersection/2/jobsearch.ftl",
        "ats_type": "workday_or_taleo",
        "portal_id": "oracle",
        "keywords": ["Intern", "Cloud Infrastructure", "Database", "Java"],
    },
    {
        "id": "salesforce",
        "name": "Salesforce France",
        "category": "Big Tech & Éditeurs",
        "country": "France",
        "careers_url": "https://salesforce.wd1.myworkdayjobs.com/External_Career_Site",
        "ats_type": "workday",
        "portal_id": "salesforce",
        "keywords": ["Intern", "Software", "Cloud", "CRM"],
    },
    {
        "id": "snowflake",
        "name": "Snowflake",
        "category": "Big Tech & Éditeurs",
        "country": "France",
        "careers_url": "https://boards-api.greenhouse.io/v1/boards/snowflake/jobs",
        "ats_type": "greenhouse",
        "portal_id": "snowflake",
        "keywords": ["Intern", "Data Cloud", "Database", "Distributed"],
    },
    {
        "id": "stmicroelectronics",
        "name": "STMicroelectronics (Tunis & France Labs)",
        "category": "Big Tech & Éditeurs",
        "country": "Tunisie",
        "careers_url": "https://stcareers.st.com/",
        "ats_type": "workday",
        "portal_id": "stmicroelectronics",
        "keywords": ["PFE", "Stage", "Embedded", "Firmware", "Semiconductor", "C++"],
    },
    {
        "id": "palantir",
        "name": "Palantir Technologies",
        "category": "Big Tech & Éditeurs",
        "country": "France",
        "careers_url": "https://boards-api.greenhouse.io/v1/boards/palantir/jobs",
        "ats_type": "greenhouse",
        "portal_id": "palantir",
        "keywords": ["Intern", "Forward Deployed", "Software", "Data"],
    },
    {
        "id": "docker",
        "name": "Docker Inc (Paris)",
        "category": "Big Tech & Éditeurs",
        "country": "France",
        "careers_url": "https://boards-api.greenhouse.io/v1/boards/docker/jobs",
        "ats_type": "greenhouse",
        "portal_id": "docker",
        "keywords": ["Intern", "DevOps", "Container", "Go"],
    },
    {
        "id": "spotify",
        "name": "Spotify",
        "category": "Big Tech & Éditeurs",
        "country": "France",
        "careers_url": "https://api.lever.co/v0/postings/spotify",
        "ats_type": "lever",
        "portal_id": "spotify",
        "keywords": ["Intern", "Backend", "Data", "Audio"],
    },
    {
        "id": "intel",
        "name": "Intel R&D France",
        "category": "Big Tech & Éditeurs",
        "country": "France",
        "careers_url": "https://jobs.intel.com/",
        "ats_type": "workday",
        "portal_id": "intel",
        "keywords": ["Intern", "AI", "Compiler", "C++", "Hardware"],
    },

    # =========================================================================
    # 5. INDUSTRIE TECH, AÉRONAUTIQUE, DÉFENSE & BANQUES (HUBS DIGITAUX)
    # =========================================================================
    {
        "id": "thales",
        "name": "Thales Group",
        "category": "Industrie Tech, Défense & Hubs",
        "country": "France",
        "careers_url": "https://thales.wd3.myworkdayjobs.com/Careers",
        "ats_type": "workday",
        "portal_id": "thales",
        "keywords": ["Stage", "PFE", "Cybersécurité", "IA", "Embarqué", "Défense"],
    },
    {
        "id": "amadeus",
        "name": "Amadeus (Sophia Antipolis R&D)",
        "category": "Industrie Tech, Défense & Hubs",
        "country": "France",
        "careers_url": "https://amadeus.com/fr/carrieres",
        "ats_type": "smartrecruiters",
        "portal_id": "amadeus",
        "keywords": ["Stage", "PFE", "Cloud", "C++", "Java", "Travel Tech"],
    },
    {
        "id": "dassault_systemes",
        "name": "Dassault Systèmes (3DS)",
        "category": "Industrie Tech, Défense & Hubs",
        "country": "France",
        "careers_url": "https://careers.3ds.com/",
        "ats_type": "smartrecruiters",
        "portal_id": "dassaultsystemes",
        "keywords": ["Stage", "PFE", "3D", "Cloud", "C++", "Jumeaux Numériques"],
    },
    {
        "id": "orange",
        "name": "Orange & Orange Business",
        "category": "Industrie Tech, Défense & Hubs",
        "country": "France",
        "careers_url": "https://orange.jobs/",
        "ats_type": "smartrecruiters",
        "portal_id": "orange",
        "keywords": ["Stage", "PFE", "Cloud", "Cyberdefense", "5G", "IA"],
    },
    {
        "id": "safran",
        "name": "Safran Digital",
        "category": "Industrie Tech, Défense & Hubs",
        "country": "France",
        "careers_url": "https://www.safran-group.com/fr/talents",
        "ats_type": "smartrecruiters",
        "portal_id": "safran",
        "keywords": ["Stage", "PFE", "Data Science", "Aéronautique", "IoT"],
    },
    {
        "id": "schneider_electric",
        "name": "Schneider Electric",
        "category": "Industrie Tech, Défense & Hubs",
        "country": "France",
        "careers_url": "https://www.se.com/fr/fr/about-us/careers/",
        "ats_type": "smartrecruiters",
        "portal_id": "schneiderelectric",
        "keywords": ["Stage", "PFE", "IoT", "Smart Energy", "Cloud"],
    },
    {
        "id": "airbus",
        "name": "Airbus Commercial & Defence",
        "category": "Industrie Tech, Défense & Hubs",
        "country": "France",
        "careers_url": "https://www.airbus.com/en/careers",
        "ats_type": "workday",
        "portal_id": "airbus",
        "keywords": ["Stage", "PFE", "Avionique", "IA", "Cybersécurité"],
    },
    {
        "id": "valeo",
        "name": "Valeo Driving Assistance Software",
        "category": "Industrie Tech, Défense & Hubs",
        "country": "France",
        "careers_url": "https://www.valeo.com/fr/carrieres/",
        "ats_type": "smartrecruiters",
        "portal_id": "valeo",
        "keywords": ["Stage", "PFE", "ADAS", "Autonomous Driving", "C++"],
    },
    {
        "id": "renault_digital",
        "name": "Renault Digital & Software Factory",
        "category": "Industrie Tech, Défense & Hubs",
        "country": "France",
        "careers_url": "https://www.renaultgroup.com/talents/",
        "ats_type": "smartrecruiters",
        "portal_id": "renaultgroup",
        "keywords": ["Stage", "PFE", "Connected Car", "Cloud", "Kotlin"],
    },
    {
        "id": "bnp_paribas",
        "name": "BNP Paribas CIB Tech",
        "category": "Industrie Tech, Défense & Hubs",
        "country": "France",
        "careers_url": "https://group.bnpparibas/emploi-carriere",
        "ats_type": "smartrecruiters",
        "portal_id": "bnpparibas",
        "keywords": ["Stage", "PFE", "Fintech", "Data", "Python", "Cloud"],
    },
    {
        "id": "societe_generale",
        "name": "Société Générale IT & Digital",
        "category": "Industrie Tech, Défense & Hubs",
        "country": "France",
        "careers_url": "https://careers.societegenerale.com/",
        "ats_type": "smartrecruiters",
        "portal_id": "societegenerale",
        "keywords": ["Stage", "PFE", "Banque", "Cybersécurité", "Agile"],
    },
    {
        "id": "natixis",
        "name": "Natixis & Groupe BPCE Tech",
        "category": "Industrie Tech, Défense & Hubs",
        "country": "France",
        "careers_url": "https://recrutement.bpce.fr/",
        "ats_type": "smartrecruiters",
        "portal_id": "groupebpce",
        "keywords": ["Stage", "PFE", "DevOps", "Data", "Cloud"],
    },
    {
        "id": "axa",
        "name": "AXA Group Tech",
        "category": "Industrie Tech, Défense & Hubs",
        "country": "France",
        "careers_url": "https://careers.axa.com/",
        "ats_type": "smartrecruiters",
        "portal_id": "axagroup",
        "keywords": ["Stage", "PFE", "InsurTech", "Cloud", "Data"],
    },
    {
        "id": "sanofi",
        "name": "Sanofi Digital & AI",
        "category": "Industrie Tech, Défense & Hubs",
        "country": "France",
        "careers_url": "https://jobs.sanofi.com/",
        "ats_type": "workday",
        "portal_id": "sanofi",
        "keywords": ["Intern", "PFE", "HealthTech", "AI", "Bioinformatics"],
    },
    {
        "id": "worldline",
        "name": "Worldline Global",
        "category": "Industrie Tech, Défense & Hubs",
        "country": "France",
        "careers_url": "https://worldline.com/fr-fr/carrieres",
        "ats_type": "smartrecruiters",
        "portal_id": "worldline",
        "keywords": ["Stage", "PFE", "Paiement", "Sécurité", "Java"],
    },
    {
        "id": "atos_eviden",
        "name": "Eviden (Atos Group)",
        "category": "Industrie Tech, Défense & Hubs",
        "country": "France",
        "careers_url": "https://eviden.com/careers/",
        "ats_type": "smartrecruiters",
        "portal_id": "eviden",
        "keywords": ["Stage", "PFE", "HPC", "Calcul Quantique", "Cloud"],
    },
]


def get_top_companies_by_country(country: str | None = None) -> list[dict[str, Any]]:
    """Retourne la liste filtrée par pays ou l'ensemble du catalogue Top 100."""
    if not country or country.lower() == "all":
        return TOP_100_COMPANIES
    c_lower = country.lower()
    return [c for c in TOP_100_COMPANIES if c["country"].lower() == c_lower]


def get_top_companies_by_ats(ats_type: str) -> list[dict[str, Any]]:
    """Retourne les entreprises utilisant un ATS spécifique (greenhouse, lever, smartrecruiters, etc.)."""
    return [c for c in TOP_100_COMPANIES if c.get("ats_type") == ats_type]
